// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCn87RCGPVaTNUaSfAeGYdj0bdvg0ihXY',
    appId: '1:148518126293:web:c6e59c19073b679646d85c',
    messagingSenderId: '148518126293',
    projectId: 'vayujal-db-for-device-customer',
    authDomain: 'vayujal-db-for-device-customer.firebaseapp.com',
    storageBucket: 'vayujal-db-for-device-customer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCObIJQlKDfl-z5zAOdwnfYf0X_kWbunjg',
    appId: '1:148518126293:android:f09dc294a2edc1a446d85c',
    messagingSenderId: '148518126293',
    projectId: 'vayujal-db-for-device-customer',
    storageBucket: 'vayujal-db-for-device-customer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT5me80HiTgszAgiDcRdm4HL1scxI8TKM',
    appId: '1:148518126293:ios:833a425d3d8cb44646d85c',
    messagingSenderId: '148518126293',
    projectId: 'vayujal-db-for-device-customer',
    storageBucket: 'vayujal-db-for-device-customer.firebasestorage.app',
    iosBundleId: 'com.example.vayujal',
  );
}
